cc_library(
    name = "am__weather_box_ino",
    srcs = ["AM_WeatherBox.ino.cc"],
    deps = [
        "//examples/AM_WeatherBox/src:server",
        "//experimental/users/jamessynge/arduino/hostuino/extras/host/arduino",
    ],
)
