# TODO(jamessynge): describe this package.

cc_library(
    name = "accel_stepper",
    hdrs = ["accel_stepper.h"],
    deps = ["//experimental/users/jamessynge/tiny-alpaca-server/extras/host/arduino"],
)
