# SweepEverything serves as a test of the timer/counter code and the pin mapping.

cc_binary(
    name = "led_fade_in_fade_out",
    srcs = ["LedFadeInFadeOut.ino.cc"],
    deps = [
        "//mcucore/extras/host/arduino",
        "//mcucore/extras/host/arduino:arduino_main",
        "//src:TinyAlpacaServer",
    ],
)
