# TODO(jamessynge): describe this package.

cc_library(
    name = "test_ip_device_setup_ino",
    srcs = ["TestIpDeviceSetup.ino.cc"],
    deps = [
        ":addresses",
        ":dhcp_class",
        ":ip_device",
    ],
)
