# Defines a base type for Observing Conditions devices.

cc_library(
    name = "observing_conditions_adapter",
    srcs = ["observing_conditions_adapter.cc"],
    hdrs = ["observing_conditions_adapter.h"],
    deps = [
        "//src:alpaca_response",
        "//src:ascom_error_codes",
        "//src:constants",
        "//src:literals",
        "//src/device_types:device_impl_base",
        "//src/device_types/cover_calibrator:cover_calibrator_constants",
        "//src/utils:inline_literal",
        "//src/utils:logging",
        "//src/utils:platform",
        "//src/utils:printable_cat",
        "//src/utils:status",
        "//src/utils:status_or",
    ],
)
