# TODO(jamessynge): describe this package.

cc_test(
    name = "ethernet_client_test",
    srcs = ["ethernet_client_test.cc"],
    deps = [
        ":ethernet_client",
        ":print_to_std_string",
        "//googletest:gunit_main",
    ],
)
