# Tests of the faux/limited host-only Ethernet3 library.

cc_test(
    name = "ethernet_client_test",
    srcs = ["ethernet_client_test.cc"],
    deps = [
        "//extras/host/ethernet3:ethernet_client",
        "//extras/test_tools:print_to_std_string",
        "//googletest:gunit_main",
    ],
)
