# Test of the TAS_DLOG and TAS_CHECK macros when ENABLED.

cc_binary(
    name = "TestLogExperimentEnabled",
    srcs = ["TestLogExperimentEnabled.ino.cc"],
    deps = [
        ":TinyAlpacaServer",
        ":arduino_main",
        ":log_experiment",
    ],
)
