# Tests of Tiny Alpaca Server src/utils/...

cc_test(
    name = "moving_average_test",
    srcs = ["moving_average_test.cc"],
    deps = [
        "//TinyAlpacaServer/src/utils:moving_average",
        "//absl/log",
        "//absl/random",
        "//absl/random:distributions",
        "//absl/time",
        "//googletest:gunit_main",
    ],
)
