# Apply Tiny Alpaca Server to the serve the AstroMakers Cover Calibrator device.

cc_binary(
    name = "CoverCalibrator",
    srcs = ["CoverCalibrator.ino.cc"],
    deps = [
        "//examples/CoverCalibrator/src:server",
        "//experimental/users/jamessynge/arduino/hostuino/extras/host/arduino",
        "//experimental/users/jamessynge/arduino/hostuino/extras/host/arduino:arduino_main",
    ],
)
