# SweepEverything serves as a test of the timer/counter code and the pin mapping.

cc_library(
    name = "sweep_everything_ino",
    srcs = ["SweepEverything.ino.cc"],
    deps = [
        ":TinyAlpacaServer",
        ":avr_timer_counter",
    ],
)
