# Demonstrates listening for ASCOM Alpaca Discovery messages and responding to them.

cc_binary(
    name = "TestAlpacaDiscoveryServer",
    srcs = ["TestAlpacaDiscoveryServer.ino.cc"],
    deps = [
        "//mcucore/extras/host/arduino",
        "//mcucore/extras/host/arduino:arduino_main",
        "//src:TinyAlpacaServer",
    ],
)
