# Test of the TAS_DLOG and TAS_CHECK macros when DISABLED.

cc_binary(
    name = "TestLogExperimentDisabled",
    srcs = ["TestLogExperimentDisabled.ino.cc"],
    deps = [
        ":TinyAlpacaServer",
        ":arduino_main",
    ],
)
