# TODO(jamessynge): describe this package.

cc_library(
    name = "pulse_spacing_modulation_ino",
    srcs = ["PulseSpacingModulation.ino.cc"],
    deps = [
        ":TinyAlpacaServer",
        ":avr_io",
    ],
)
