cc_binary(
    name = "pulse_spacing_modulation",
    srcs = ["PulseSpacingModulation.ino.cc"],
    deps = [
        "//TinyAlpacaServer/src:TinyAlpacaServer",
        "//mcucore/extras/host/arduino",
        "//mcucore/extras/host/arduino:arduino_main",
    ],
)
