# TODO(jamessynge): describe this package.

cc_library(
    name = "DecoderMemoryMeasurements/decoder_memory_measurements_ino",
    srcs = ["DecoderMemoryMeasurements/DecoderMemoryMeasurements.ino.cc"],
    tags = [
        "local",
        "manual",
    ],
    deps = [":tiny_alpaca_server"],
)

cc_library(
    name = "EncoderMemoryMeasurements/encoder_memory_measurements_ino",
    srcs = ["EncoderMemoryMeasurements/EncoderMemoryMeasurements.ino.cc"],
    tags = [
        "local",
        "manual",
    ],
    deps = [":tiny_alpaca_server"],
)

cc_library(
    name = "TestLiteralInPROGMEM/test_literal_in_progmem_ino",
    srcs = ["TestLiteralInPROGMEM/TestLiteralInPROGMEM.ino.cc"],
    tags = [
        "local",
        "manual",
    ],
    deps = [":tiny_alpaca_server"],
)
