# TODO(jamessynge): describe this package.

cc_library(
    name = "device_impl_base",
    srcs = ["device_impl_base.cc"],
    hdrs = ["device_impl_base.h"],
    deps = [
        ":alpaca_request",
        ":alpaca_response",
        ":ascom_error_codes",
        ":constants",
        ":counting_print",
        ":device_info",
        ":device_interface",
        ":http_response_header",
        ":json_encoder",
        ":literals",
        ":o_print_stream",
        ":platform",
        ":status",
        ":status_or",
    ],
)
