# TODO(jamessynge): describe this package.

cc_library(
    name = "open_and_close_cover_with_pwm_ino",
    srcs = ["OpenAndCloseCoverWithPwm.ino.cc"],
    deps = [
        ":TinyAlpacaServer",
    ],
)
