cc_binary(
    name = "open_and_close_cover_with_pwm",
    srcs = ["OpenAndCloseCoverWithPwm.ino.cc"],
    deps = [
        "//extras/host/arduino",
        "//extras/host/arduino:arduino_main",
        "//src:TinyAlpacaServer",
    ],
)
