# TODO(jamessynge): describe this package.

cc_library(
    name = "switch_adapter",
    srcs = ["switch_adapter.cc"],
    hdrs = ["switch_adapter.h"],
    deps = [
        "//src:alpaca_response",
        "//src:ascom_error_codes",
        "//src:constants",
        "//src:literals",
        "//src/device_types:device_impl_base",
        "//src/utils:platform",
        "//src/utils:status_or",
    ],
)
