# With Arduino Builder, can be used to measure the amount of memory
# required when various objects/code is referenced by the sketch.

load(
    "//TinyAlpacaServer/extras/dev_tools:build_config.bzl",
    "build_config",
)

package(
    default_copts = build_config.default_copts,
)

cc_binary(
    name = "encoder_memory_measurements",
    srcs = ["EncoderMemoryMeasurements.ino.cc"],
    deps = [
        "//TinyAlpacaServer/src:TinyAlpacaServer",
        "//mcucore/extras/host/arduino",
        "//mcucore/extras/host/arduino:arduino_main",
    ],
)
