#ifndef TINY_ALPACA_SERVER_EXTRAS_HOST_ETHERNET5500_ETHERNET_CONFIG_H_
#define TINY_ALPACA_SERVER_EXTRAS_HOST_ETHERNET5500_ETHERNET_CONFIG_H_

#include <inttypes.h>

namespace alpaca {

typedef uint8_t SOCKET;
#define MAX_SOCK_NUM 8

}  // namespace alpaca

#endif  // TINY_ALPACA_SERVER_EXTRAS_HOST_ETHERNET5500_ETHERNET_CONFIG_H_
