#ifndef TINY_ALPACA_SERVER_EXTRAS_HOST_ETHERNET3_ETHERNET_CONFIG_H_
#define TINY_ALPACA_SERVER_EXTRAS_HOST_ETHERNET3_ETHERNET_CONFIG_H_

#include <cstdint>

namespace alpaca {

typedef std::uint8_t SOCKET;
#define MAX_SOCK_NUM 8

}  // namespace alpaca

#endif  // TINY_ALPACA_SERVER_EXTRAS_HOST_ETHERNET3_ETHERNET_CONFIG_H_
