# Experiment with edge triggered pin interrupts.

cc_binary(
    name = "bouncy_switch",
    srcs = ["BouncySwitch.ino.cc"],
    deps = [
        "//TinyAlpacaServer/src:TinyAlpacaServer",
        "//mcucore/extras/host/arduino",
        "//mcucore/extras/host/arduino:arduino_main",
    ],
)
